---

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Enable nginx
  service:
    name: nginx
    enabled: yes
