---

- name: Update Rails App
  hosts: production
  remote_user: ubuntu
  become: yes
  roles:
    - role: update_app
      param_app_name: "{{ app_name }}"
      param_database_name: "{{ db_name }}"
      param_master_key: "{{ freebenta_master_key }}"
      param_branch: "{{ freebenta_branch }}"
      param_git_name: "{{ freebenta_git_name }}"
      param_ruby_version: 2.5.3
      param_commit: de0b030
