---

- name: Recreate database with seed data
  hosts: production
  remote_user: ubuntu
  become: yes
  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

  tasks:

    - name: Stop web application
      service:
        name: puma-{{ app_name }}
        state: stopped

    - name: Destroy {{ db_name }} database
      become_user: postgres
      postgresql_db:
        login_user: postgres
        name: freebenta_db
        state: absent

    - name: Create {{ db_name }} database
      become_user: postgres
      postgresql_db:
        login_user: postgres
        name: freebenta_db
        state: present

    - name: Create {{ db_user }} database user
      become_user: postgres
      postgresql_user:
        login_user: postgres
        name: freebenta_user
        password: default
        db: freebenta_db
        priv: ALL
        state: present

    - name: Load {{ db_name }} database schema
      become_user: "{{ dedicated_sys_user }}"
      shell: ~/.rbenv/shims/bundle exec rails db:schema:load
      args:
        chdir: /var/www/{{ app_name }}/application
      environment:
        DISABLE_DATABASE_ENVIRONMENT_CHECK: 1

    - name: Seed database with test data
      become_user: "{{ dedicated_sys_user }}"
      shell: ~/.rbenv/shims/bundle exec rake db:seed
      args:
        chdir: /var/www/{{ app_name }}/application

    - name: Restart puma
      service:
        name: puma-{{ app_name }}
        state: restarted

