---

- name: Install Rails App
  hosts: production
  remote_user: ubuntu
  become: yes
  roles:
    - role: install_app
      tags: install_app
      param_app_name: freebenta
      param_master_key: "{{ freebenta_master_key }}"
      param_branch: "{{ freebenta_branch }}"
      param_git_name: "{{ freebenta_git_name }}"
      param_commit: "{{ freebenta_commit }}"
      param_ruby_version: 2.5.3
      param_bind_port: 10000
      param_database_name: freebenta_db
      param_database_user: freebenta_user
      param_database_password: default
      param_database_host: localhost
      param_domains:
        - freebenta.philippinedev.com
