---

- name: Copy {{ param_app_name }} database configuration
  template:
    src: database.yml.j2
    dest: /var/www/{{ param_app_name }}/shared/config/database.yml
    owner: "{{ param_app_name }}"
    group: "{{ param_app_name }}"
    mode: 0600

- name: Install PostgreSQL development headers
  apt:
    name: libpq-dev
    state: present
    update_cache: yes

- name: Create {{ param_app_name }} database
  become_user: postgres
  postgresql_db:
    login_user: postgres
    name: "{{ param_database_name }}"
    state: present

- name: Create {{ param_app_name }} database user
  become_user: postgres
  postgresql_user:
    login_user: postgres
    name: "{{ param_database_user }}"
    password: "{{ param_database_password }}"
    db: "{{ param_database_name }}"
    priv: ALL
    state: present
